<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>net9.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NoWarn>8656</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="($(RuntimeIdentifier) == '' and $([MSBuild]::IsOSPlatform('Windows'))) or $(RuntimeIdentifier.StartsWith('win'))">
		<DefineConstants>WINDOWS</DefineConstants>
		<IsWindows>true</IsWindows>
	</PropertyGroup>

	<PropertyGroup Condition="($(RuntimeIdentifier) == '' and $([MSBuild]::IsOSPlatform('Linux'))) or $(RuntimeIdentifier.StartsWith('linux'))">
		<DefineConstants>LINUX</DefineConstants>
		<IsLinux>true</IsLinux>
	</PropertyGroup>

	<!-- Managed packages -->
	<ItemGroup>
		<PackageReference Include="Hexa.NET.SDL3" Version="1.2.17" />
		<PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
		<PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
		<PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
		<PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
		<PackageReference Include="GpuMemoryAllocator.Vulkan" Version="3.3.0-0.2.0" />

		<PackageReference Include="StbImageSharp" Version="2.30.16" />
		<PackageReference Include="FontStashSharp.PlatformAgnostic" Version="1.5.6" />
	</ItemGroup>

	<!-- Native Packages -->
	<ItemGroup>
		<PackageReference Include="GpuMemoryAllocator.vma" Version="3.3.0-0.2.0" />
	</ItemGroup>

</Project>
