<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <Version>1.1.0</Version>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>MonoGame.ImGuiNet</PackageId>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Chisel.Framework\Chisel.Framework.csproj" />
      <ProjectReference Include="..\Chisel.Resource.Builder\Chisel.Resource.Builder.csproj" />
    </ItemGroup>
</Project>