<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>net9.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Title>Chisel 2</Title>
		<Company>Elgen Tidwell, Torin Sevilla</Company>
		<NeutralLanguage>en</NeutralLanguage>
	</PropertyGroup>

	<PropertyGroup Condition="($(RuntimeIdentifier) == '' and $([MSBuild]::IsOSPlatform('Windows'))) or $(RuntimeIdentifier.StartsWith('win'))">
		<DefineConstants>WINDOWS</DefineConstants>
		<IsWindows>true</IsWindows>
	</PropertyGroup>

	<PropertyGroup Condition="($(RuntimeIdentifier) == '' and $([MSBuild]::IsOSPlatform('Linux'))) or $(RuntimeIdentifier.StartsWith('linux'))">
		<DefineConstants>LINUX</DefineConstants>
		<IsLinux>true</IsLinux>
	</PropertyGroup>

</Project>
